import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Toaster } from "react-hot-toast";

// Load Google Fonts
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  display: "swap",
});

// Metadata
export const metadata: Metadata = {
  title: "HMS - Hospital Management System",
  description: "Generated by create next app",
};

// Root Layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${robotoMono.variable} antialiased bg-gray-50`}
      >
        <Providers>
          {children}
          {/* Global Toast Notifications */}
          <Toaster
            position="top-right"
            toastOptions={{
              success: {
                style: {
                  background: "#4ade80", // green-400
                  color: "#fff",
                  fontWeight: "500",
                },
              },
              error: {
                style: {
                  background: "#ef4444", // red-500
                  color: "#fff",
                  fontWeight: "500",
                },
              },
            }}
          />
        </Providers>
      </body>
    </html>
  );
}
